name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v3
    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel
    - name: Build wheel
      run: |
        python -m cibuildwheel --output-dir dist
    - uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist/


  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/master')
        with:
          skip-existing: true
